SET DEFINE OFF;
Insert into HR.DEPARTMENTS
   (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID)
 Values
   (10, 'Administration', 200, 1700);
Insert into HR.DEPARTMENTS
   (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID)
 Values
   (20, 'Marketing', 201, 1800);
Insert into HR.DEPARTMENTS
   (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID)
 Values
   (30, 'Purchasing', 114, 1700);
Insert into HR.DEPARTMENTS
   (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID)
 Values
   (40, 'Human Resources', 203, 2400);
Insert into HR.DEPARTMENTS
   (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID)
 Values
   (50, 'Shipping', 121, 1500);
Insert into HR.DEPARTMENTS
   (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID)
 Values
   (60, 'IT', 103, 1400);
Insert into HR.DEPARTMENTS
   (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID)
 Values
   (70, 'Public Relations', 204, 2700);
Insert into HR.DEPARTMENTS
   (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID)
 Values
   (80, 'Sales', 145, 2500);
Insert into HR.DEPARTMENTS
   (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID)
 Values
   (90, 'Executive', 100, 1700);
Insert into HR.DEPARTMENTS
   (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID)
 Values
   (100, 'Finance', 108, 1700);
Insert into HR.DEPARTMENTS
   (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID)
 Values
   (110, 'Accounting', 205, 1700);
Insert into HR.DEPARTMENTS
   (DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID)
 Values
   (120, 'Treasury', 1700);
Insert into HR.DEPARTMENTS
   (DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID)
 Values
   (130, 'Corporate Tax', 1700);
Insert into HR.DEPARTMENTS
   (DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID)
 Values
   (140, 'Control And Credit', 1700);
Insert into HR.DEPARTMENTS
   (DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID)
 Values
   (150, 'Shareholder Services', 1700);
Insert into HR.DEPARTMENTS
   (DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID)
 Values
   (160, 'Benefits', 1700);
Insert into HR.DEPARTMENTS
   (DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID)
 Values
   (170, 'Manufacturing', 1700);
Insert into HR.DEPARTMENTS
   (DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID)
 Values
   (180, 'Construction', 1700);
Insert into HR.DEPARTMENTS
   (DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID)
 Values
   (190, 'Contracting', 1700);
Insert into HR.DEPARTMENTS
   (DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID)
 Values
   (200, 'Operations', 1700);
Insert into HR.DEPARTMENTS
   (DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID)
 Values
   (210, 'IT Support', 1700);
Insert into HR.DEPARTMENTS
   (DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID)
 Values
   (220, 'NOC', 1700);
Insert into HR.DEPARTMENTS
   (DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID)
 Values
   (230, 'IT Helpdesk', 1700);
Insert into HR.DEPARTMENTS
   (DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID)
 Values
   (240, 'Government Sales', 1700);
Insert into HR.DEPARTMENTS
   (DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID)
 Values
   (250, 'Retail Sales', 1700);
Insert into HR.DEPARTMENTS
   (DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID)
 Values
   (260, 'Recruiting', 1700);
Insert into HR.DEPARTMENTS
   (DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID)
 Values
   (270, 'Payroll', 1700);
COMMIT;
